// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "回傳 Pong 確認伺服器存活",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "健康檢查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "取得所有記帳紀錄",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "取得列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "建立一筆新的收入或支出紀錄",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "新增記帳",
                "parameters": [
                    {
                        "description": "記帳資料",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Transaction": {
            "type": "object",
            "required": [
                "amount",
                "category",
                "date",
                "type"
            ],
            "properties": {
                "amount": {
                    "description": "Amount: 金額",
                    "type": "number",
                    "example": 150
                },
                "category": {
                    "description": "Category: 類別 (如: Food, Transport)",
                    "type": "string",
                    "example": "Food"
                },
                "created_at": {
                    "description": "CreatedAt: 建立時間",
                    "type": "string"
                },
                "date": {
                    "description": "Date: 日期字串 \"YYYY-MM-DD\"\n為了配合前端傳來的格式，我們先用 string 存，方便處理",
                    "type": "string",
                    "example": "2026-01-14"
                },
                "id": {
                    "description": "ID: MongoDB 自動生成的唯一識別碼\nomitempty: 如果是空的 (建立時) 就不傳這個欄位給 MongoDB，讓它自己生",
                    "type": "string"
                },
                "note": {
                    "description": "Note: 備註 (選填)",
                    "type": "string",
                    "example": "午餐吃牛肉麵"
                },
                "type": {
                    "description": "Type: \"income\" 或 \"expense\"\nbinding:\"required\": Gin 會幫我們檢查這個欄位必填",
                    "type": "string",
                    "enum": [
                        "income",
                        "expense"
                    ],
                    "example": "expense"
                },
                "updated_at": {
                    "description": "UpdatedAt: 更新時間",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FinTrack API",
	Description:      "這是個人記帳工具 FinTrack 的後端 API 文件",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
